default:
  app_url: "http://localhost:8081/?{dataset}/{model_run_id}"

development:
  app_url: "/nhp/dev/outputs/?{dataset}/{model_run_id}"

production:
  app_url: "/nhp/{app_version}/outputs/?{outputs_app_uri}"