default:
  golem_name: outputs
  golem_version: 0.0.0.9000
  app_prod: no

  pod_measures:
    aae:
      name: "A&E"
      pods:
        aae_type-01:
          name: "Type 1 Department"
          measures:
            - ambulance
            - walk-in
        aae_type-02:
          name: "Type 2 Department"
          measures:
            - ambulance
            - walk-in
        aae_type-03:
          name: "Type 3 Department"
          measures:
            - ambulance
            - walk-in
        aae_type-04:
          name: "Type 4 Department"
          measures:
            - ambulance
            - walk-in
    ip:
      name: "Inpatients"
      pods:
        ip_elective_admission:
          name: "Elective Admission"
          measures:
            - admissions
            - beddays
        ip_elective_daycase:
          name: "Daycase Admission"
          measures:
            - admissions
            - beddays
        ip_non-elective_admission:
          name: "Non-Elective Admission"
          measures:
            - admissions
            - beddays
        ip_non-elective_birth-episode:
          name: "Birth Episode"
          measures:
            - admissions
            - beddays
    op:
      name: "Outpatients"
      pods:
        op_first:
          name: "First Outpatient Attendance"
          measures:
            - attendances
            - tele_attendances
        op_follow-up:
          name: "Follow-up Outpatient Attendance"
          measures:
            - attendances
            - tele_attendances
        op_procedure:
          name: "Outpatient Procedure"
          measures:
            - attendances
            - procedures
  aggregations:
    - default
    - sex+age_group
    - sex+tret_spef

production:
  app_prod: yes
dev:
  golem_wd: !expr here::here()
  datasets_path: !expr here::here("..", "data")
