---
title: "NHP Parameters Report"
subtitle: "Scenario: `r params$r$params$scenario`"
output:
  html_document:
    toc: true
    toc_depth: 6
    toc_float:
      collapsed: true
params:
  r: NA
---

```{r}
#| label: setup
#| echo: false

knitr::opts_chunk$set(error = TRUE, echo = FALSE)

# Check if fct_report functions are loaded by seeing if one exists in the env
# (allows for both local and remote rendering)
if (!exists("mod_info_downloads_download_json")) {
  source(
    here::here("R", "fct_report.R"),
    local = knitr::knit_global()
  )
}
```

```{css}
h1 {
  font-size: 32px;
}

h2 {
  font-size: 28px;
}

h3 {
  font-size: 26px;
}

h4 {
  font-size: 24px;
}

h5 {
  font-size: 22px;
}

h6 {
  font-size: 20px;
}

p {
  font-size: 16px;
}
```

```{r}
#| label: setup-params

p <- get_params(params$r)
```

# Notes

This report provides the parameter selections for the selected model scenario (`r params$r$params$scenario`) and the rationale given for these choices.

See [the model project information site](https://connect.strategyunitwm.nhs.uk/nhp/project_information) for an overview, user guide and methodology for the model and the outputs app.

# Metadata

This table shows the metadata for the selected model run:

```{r}
#| label: params-model-run

tabulate_model_run_info(p)
```

# Parameters

```{r echo=F, results='asis'}
#| label: params-expand

p |> param_tables_to_list() |> expand_param_tables_to_rmd()
```

# Rationale

```{r echo=F, results='asis'}
#| label: rationale-expand
#| 
reasons <- p$reasons

if (is.null(reasons)) {
  cat("No rationale provided.\n\n")
} else {
   expand_reasons_to_rmd(reasons)
}
```
