name: "Connect Publish (dev)"
on:
  push:
    branches: [main]

jobs:
  connect-publish-dev:
    uses: ./.github/workflows/connect-publish.yaml
    with:
      namespace: nhp_dev
    secrets: inherit
