name: "Connect Publish (dev)"
on:
  release:
    types: [published]

jobs:
  connect-publish-dev:
    uses: ./.github/workflows/connect-publish.yaml
    with:
      namespace: nhp_dev
    secrets: inherit