name: "Connect Publish (dev)"
on:
  push:
    branches: [main]

jobs:
  connect-publish-dev:
    name: "Connect Publish (dev)"
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2
        with:
          profile: '"prod"'

      - name: Generate manifest.json
        run: Rscript dev/generate_manifest.R
        
      - name: Publish Connect content
        uses: rstudio/actions/connect-publish@main
        with:
          url: ${{ secrets.RSCONNECT_URL }}
          api-key: ${{ secrets.RSCONNECT_API_KEY }}
          access-type: acl
          force: true
          dir: .:outputs
          namespace: nhp_dev
