name: "Connect Publish"

on:
  workflow_call:
    inputs:
      namespace:
        required: true
        type: string
    secrets:
      RSCONNECT_URL:
        required: true
      RSCONNECT_API_KEY:
        required: true

jobs:
  connect-publish:
    name: "Connect Publish"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Publish Connect content
        uses: rstudio/actions/connect-publish@main
        with:
          url: ${{ secrets.RSCONNECT_URL }}
          api-key: ${{ secrets.RSCONNECT_API_KEY }}
          access-type: acl
          force: true
          dir: .:outputs
          namespace: ${{ inputs.namespace }}
