name: "Connect Publish (prod)"
on:
  release:
    types: [published]

jobs:
  connect-publish-prod:
    name: "Connect Publish (prod)"
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # use the prod renv profile, even on dev (dev contains local development dependencies)
      RENV_PROFILE: prod

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2
        with:
          profile: '"prod"'

      - name: Generate manifest.json
        run: Rscript dev/generate_manifest.R

      - name: Publish Connect content
        uses: rstudio/actions/connect-publish@main
        with:
          url: ${{ secrets.RSCONNECT_URL }}
          api-key: ${{ secrets.RSCONNECT_API_KEY }}
          access-type: acl
          force: true
          dir: .:outputs
          namespace: nhp
