name: "Connect Publish (prod)"
on:
  release:
    types: [published]

jobs:
  connect-publish-prod:
    uses: ./.github/workflows/connect-publish.yaml
    with:
      namespace: nhp
    secrets: inherit