name: "Connect Publish (dev)"
on:
  push:
    branches: [main]

jobs:
  connect-publish-dev:
    name: "Connect Publish: Dev"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update manifest.json
        run: node update_manifest.js

      - name: Publish Connect content
        uses: rstudio/actions/connect-publish@main
        env:
          CONNECT_ENV_SET_AZ_STORAGE_CONTAINER: ${{ secrets.AZ_STORAGE_CONTAINER }}
          CONNECT_ENV_SET_AZ_STORAGE_EP: ${{ secrets.AZ_STORAGE_EP }}
          CONNECT_ENV_SET_NHP_ENCRYPT_KEY: ${{ secrets.NHP_ENCRYPT_KEY }}
        with:
          url: ${{ secrets.RSCONNECT_URL }}
          api-key: ${{ secrets.RSCONNECT_API_KEY }}
          access-type: logged_in
          force: true
          dir: .:outputs
          namespace: nhp/dev