name: "Connect Publish (manual)"
on:
  workflow_dispatch:
    inputs:
      namespace:
        required: true
        type: string
      environment:
        description: "The environment to deploy to"
        required: true
        type: choice
        default: "production"
        options:
          - "production"
          - "new-production"
  workflow_call:
    inputs:
      namespace:
        required: true
        type: string
      inputs_data_version:
        required: true
        type: string
      environment:
        description: "The environment to deploy to"
        required: true
        type: string
        default: "production"

jobs:
  connect-publish:
    name: "Connect Publish: ${{ inputs.namespace }} [${{ inputs.environment }}]"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: Update manifest.json
        run: node update_manifest.js

      - name: Publish Connect content
        uses: rstudio/actions/connect-publish@main
        env:
          CONNECT_ENV_SET_AZ_STORAGE_CONTAINER: ${{ secrets.AZ_STORAGE_CONTAINER }}
          CONNECT_ENV_SET_AZ_STORAGE_EP: ${{ secrets.AZ_STORAGE_EP }}
          CONNECT_ENV_SET_NHP_ENCRYPT_KEY: ${{ secrets.NHP_ENCRYPT_KEY }}
        with:
          url: ${{ secrets.RSCONNECT_URL }}
          api-key: ${{ secrets.RSCONNECT_API_KEY }}
          access-type: logged_in
          force: true
          dir: .:outputs
          namespace: nhp/${{ inputs.namespace }}