name: "Connect Publish (prod)"
on:
  release:
    types: [published]

jobs:
  connect-publish-prod:
    name: "Connect Publish: Production"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get version
        run: |
          VERSION=`echo ${{ github.ref_name }} | awk 'BEGIN { FS="."; } { print ""$1"-"$2; }'`
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update manifest.json
        run: node update_manifest.js
        
      - name: Publish Connect content
        uses: rstudio/actions/connect-publish@main
        env:
          CONNECT_ENV_SET_NHP_APP_VERSION: ${{ env.VERSION }}
          CONNECT_ENV_SET_AZ_STORAGE_CONTAINER: ${{ secrets.AZ_STORAGE_CONTAINER }}
          CONNECT_ENV_SET_AZ_STORAGE_EP: ${{ secrets.AZ_STORAGE_EP }}
          CONNECT_ENV_SET_NHP_ENCRYPT_KEY: ${{ secrets.NHP_ENCRYPT_KEY }}
        with:
          url: ${{ secrets.RSCONNECT_URL }}
          api-key: ${{ secrets.RSCONNECT_API_KEY }}
          access-type: acl
          force: true
          dir: .:outputs
          namespace: nhp/${{ env.VERSION }}
